CREATE DATABASE IF NOT EXISTS eims;

USE eims;

DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
    acct VARCHAR(20) NOT NULL,
    pwd VARCHAR(20) NOT NULL,
    PRIMARY KEY (acct)
);

TRUNCATE TABLE admin;

DROP TABLE IF EXISTS emp;

CREATE TABLE emp (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    dept VARCHAR(20) NOT NULL,
    job VARCHAR(20) NOT NULL,
    sal DOUBLE NOT NULL,
    PRIMARY KEY (id)
);

TRUNCATE TABLE emp;